[package]
name = "torrent-search"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]
edition = "2018"
[dependencies]
select = "^0.4"
hyper = "^0.10"
hyper-native-tls = "^0.3"
docopt = "^1.1"
ansi_term = "^0.12"
serde = { version = "1", features = ["derive"] }
env_logger = "^0.7"
log = "^0.4"
